version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # تأكد من أن رابط قاعدة البيانات في .env أو هنا يشير إلى الخدمة mongo:
      # DATABASE_URI=mongodb://mongo:27017/payload-db

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
